language: python
python:
  - 3.7
services:
- docker
cache:
  directories:
    - node_modules
install:
  - pip install -r requirements.txt
  - nvm install 0.10
  - npm install
script: 
    - npm install -g serverless
    - sls deploy