dist: xenial
language: python
python:
  - "3.7"
services:
- docker
cache:
  directories:
    - node_modules
    - $HOME/.nvm
    - $HOME/.cache/pip
install:
  - pip install -r requirements.txt
  - nvm install node
  - npm install
  - npm install -g serverless
script: 
    - serverless deploy