# Built using Serverless
# Helithumper 2019

service: dprogrammer-grabber
provider:
  name: aws
  runtime: python3.7
  region: us-east-1
functions:
  grab_and_post:
    handler: handler.grab_and_post
    events:
    - schedule:
        rate: cron(0 8 * * ? *)
        enabled: false
